#ifndef CANON_CORE_H
#define CANON_CORE_H

#pragma once

/* Generated by cbindgen from the canon-core `c-binding` feature. DO NOT EDIT. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Status: the call succeeded and the output params are populated.
 */
#define CANON_OK 0

/**
 * Status: the call failed; `*err_out` holds a NUL-terminated UTF-8 message the caller must free.
 */
#define CANON_ERR 1

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Canonical bytes over a tagged-JSON-text input.
 *
 * `tagged_json`  : caller-owned NUL-terminated UTF-8 C string (the DENC-produced tagged text).
 * `bytes_out`    : receives a heap pointer to the canonical bytes (free with `canon_bytes_free`).
 * `len_out`      : receives the length in bytes.
 * `err_out`      : on failure receives a heap error string (free with `canon_string_free`).
 *
 * Returns `CANON_OK` or `CANON_ERR`. Byte-identical to `canon_core::canonical_bytes_from_json`.
 *
 * # Safety
 * All pointers must be valid per the module ownership contract.
 */
int canon_canonical_bytes_from_json(const char *tagged_json,
                                    uint8_t **bytes_out,
                                    uintptr_t *len_out,
                                    char **err_out);

/**
 * Digest (hex) over a tagged-JSON-text input under a profile.
 *
 * `tagged_json` : caller-owned NUL-terminated UTF-8 C string.
 * `profile`     : caller-owned NUL-terminated UTF-8 C string (one of the four canon profiles).
 * `digest_out`  : receives a heap NUL-terminated hex C string (free with `canon_string_free`).
 * `err_out`     : on failure receives a heap error string (free with `canon_string_free`).
 *
 * Returns `CANON_OK` or `CANON_ERR`. Byte-identical to `canon_core::digest_from_json`.
 *
 * # Safety
 * All pointers must be valid per the module ownership contract.
 */
int canon_digest_from_json(const char *tagged_json,
                           const char *profile,
                           char **digest_out,
                           char **err_out);

/**
 * Free a byte buffer returned by `canon_canonical_bytes_from_json`.
 *
 * # Safety
 * `ptr`/`len` must be exactly the pair a `canon_canonical_bytes_from_json` call wrote, and must be
 * freed at most once. A null `ptr` is a no-op.
 */
void canon_bytes_free(uint8_t *ptr, uintptr_t len);

/**
 * Free a C string returned by `canon_digest_from_json` or via an `err_out` param.
 *
 * # Safety
 * `ptr` must be a string this crate returned, freed at most once. A null `ptr` is a no-op.
 */
void canon_string_free(char *ptr);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CANON_CORE_H */
